rewards:
  1:
    chance: 30
    reward: "/op rewardedcarton"
  2:
    chance: 60
    reward: "/give rewardedcarton diamond 1"
  3:
    chance: 10
    reward: "/gamemode creative rewardedcarton"
spawnMessage: "&aA new crate has been released!"
foundMessage: "&a{player} &chas found the crate at: &a{location}"
radius: 1000
crateType: ender_chest